# Generated by Django 4.1.4 on 2022-12-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depName', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=8)),
                ('userImage', models.ImageField(height_field=20, upload_to='upload/', width_field=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subName', models.CharField(max_length=150, unique=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='myapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=5000)),
                ('dateCreate', models.DateTimeField(auto_now_add=True)),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques', to='myapp.subject')),
                ('userCreate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ques', to='myapp.user')),
            ],
        ),
    ]
