# Generated by Django 4.1.4 on 2022-12-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userImage',
            field=models.ImageField(height_field=200, upload_to='upload/', width_field=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(max_length=150),
        ),
    ]
