# Generated by Django 4.1.4 on 2022-12-09 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_userimage_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userImage',
        ),
    ]
